repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        files: \.(TcPOU|TcDUT|TcGVL)$

-   repo: https://github.com/pcdshub/pre-commit-hooks.git
    rev: v1.7.1
    hooks:
    # checks if the option "Write product version if files" is set to false, see https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_plc_intro/3260207243.html&id=
    -   id: no-product-version
    # adds new line to ST files to reduce git changes, adds a new line also at the start of the file
    #-   id: twincat-st-newline
    # remove line ids from ST files
    -   id: twincat-lineids-remover
