<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="NEGX" Id="{3b921653-ec23-401e-b1c2-5ca875e924f2}" SpecialFunc="None">
    <Declaration><![CDATA[(*
version 1.0	26. oct. 2008
programmer 	hugo
tested by	tobias

This function returns -X

*)
FUNCTION NEGX : REAL
VAR_INPUT
	X : REAL;
END_VAR




]]></Declaration>
    <Implementation>
      <ST><![CDATA[NEGX := -X;


(* revision history
hm	26. oct. 2008	rev 1.0
	original version


*)
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>