<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="WINDOW" Id="{24b424c6-fd0c-4c43-a987-2de1674349c4}" SpecialFunc="None">
    <Declaration><![CDATA[(*
	version 1.1	22 jan 2007
	programmer 	hugo
	tested BY	tobias

this checks a signal if the signal is between the upper and lower limit
*)
FUNCTION WINDOW : BOOL
VAR_INPUT
	low : REAL;
	in : REAL;
	high : REAL;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[WINDOW := in < high AND in > low;


(* revision history
hm	22.1.2007	rev 1.1
	changed the order of inputs to low, in, high

*)]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
