<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="BIT_TOGGLE_W" Id="{f47d6386-6305-4dbd-ac0f-05e17dbe8b94}" SpecialFunc="None">
    <Declaration><![CDATA[(*
version 1.0 18. oct. 2008
programmer 	hugo
tested by	tobias

this function toggles a bit of a WORD at position pos.

*)
FUNCTION BIT_TOGGLE_W : WORD
VAR_INPUT
	IN : WORD;
	POS : INT;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[BIT_TOGGLE_W := SHL(WORD#1, POS) XOR IN;



(* revision history
hm	18. oct. 2008	rev 1.0
	original version


*)
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>