<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="DW_TO_REAL" Id="{e338f6d7-c40f-471d-b5e8-40b7e78c7185}" SpecialFunc="None">
    <Declaration><![CDATA[(*
version 1.0	18. apr. 2008
programmer 	hugo
tested by		tobias

this function converts a DWORD to REAL in a bitwise manner.
*)
FUNCTION DW_TO_REAL : REAL
VAR_INPUT
	X : DWORD;
END_VAR
VAR
	pt : POINTER TO REAL;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[pt := ADR(X);
DW_TO_REAL := pt^;

(* revision history
hm	18. apr. 2008
	original version

*)]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
