<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CIRCLE_C" Id="{c5f03b02-f5f8-4df6-b315-93a8ec7b3616}" SpecialFunc="None">
    <Declaration><![CDATA[(*
version 1.1	22 feb 2008
programmer 	hugo
tested by		tobias

circle_C calculates the Circumference of a circle  if ax = 360 the whole circle is calculated

*)
FUNCTION CIRCLE_C : REAL
VAR_INPUT
	Rx : REAL;
	Ax : REAL;
END_VAR



]]></Declaration>
    <Implementation>
      <ST><![CDATA[circle_C := 1.7453293E-2 * Rx * Ax;

(* revision histroy
hm	16. oct 2007	rev 1.0
	original version

hm	22. feb 2008	rev 1.1
	improved performance
*)]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
