<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MINUTE_OF_DT" Id="{cce19d47-f4ff-461a-a195-9aa591cf2919}" SpecialFunc="None">
    <Declaration><![CDATA[(*
	version 1.0	6. jun. 2008
	programmer 	oscat
	tested BY	oscat

MINUTE_OF_DT returns the current minute (minute of the hour) of a DT variable

*)
FUNCTION MINUTE_OF_DT : INT
VAR_INPUT
	XDT : DT;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[MINUTE_OF_DT := DWORD_TO_INT(DT_TO_DWORD(XDT) MOD 3600) / 60;


(* revision history
hm		6.9.2008	rev 1.0
	original version


*)]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>