<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="String_Test" Id="{9a42e009-eb20-4d8c-bcd8-047061b12bfc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK String_Test EXTENDS TcUnit.FB_TestSuite
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>