<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="OM_TO_F" Id="{2491f1cc-b18d-4425-8cbd-25501bb6e4db}" SpecialFunc="None">
    <Declaration><![CDATA[(*
version 1.1	18. oct. 2008
programmer 	hugo
tested by		tobias

this function converts Omega F to frequency
F = OM / (2*PI)
*)
FUNCTION OM_TO_F : REAL
VAR_INPUT
	OM : REAL;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[OM_TO_F := OM / math.PI2;


(* revision history
hm	22. jan. 2007	rev 1.0
	original version

hm	18. oct. 2008	rev 1.1
	using math constants

*)]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
