<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PT_TO_F" Id="{13dfffec-430e-4efb-8ca7-6883f004a438}" SpecialFunc="None">
    <Declaration><![CDATA[(*
version 1.1	11. mar. 2009
programmer 	hugo
tested by		tobias

this function converts periode time to frequency
*)
FUNCTION PT_TO_F : REAL
VAR_INPUT
	PT : TIME;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[PT_TO_F := 1000.0 / DWORD_TO_REAL(TIME_TO_DWORD(PT));


(*	revision history
hm	4. aug. 2006	rev 1.0
	original version

hm	11. mar. 2009	rev 1.1
	real constants updated to new systax using dot

*)
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
