<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="RANGE_TO_WORD" Id="{5bb7e912-2005-49b0-9511-e16e808948c4}" SpecialFunc="None">
    <Declaration><![CDATA[(*
version 1.0	9. jan 2008
programmer 	hugo
tested by		tobias

Range_to_word converts a real value between low and high into a byte

*)
FUNCTION RANGE_TO_WORD : WORD
VAR_INPUT
	X : REAL;
	low : REAL;
	high : REAL;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[RANGE_TO_WORD := DINT_TO_WORD(TRUNC_INT((LIMIT(low,X,high)-low) * 65535.0 / (high - low)));


(* revision history
hm	9. jan 2008		rev 1.0
	original version

*)
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
