<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="WORD_TO_RANGE" Id="{c59ff76c-add4-409a-82f7-32086b42ebb4}" SpecialFunc="None">
    <Declaration><![CDATA[(*
version 1.1	10. mar. 2009
programmer 	hugo
tested by		tobias

Word_to_Range converts a Byte into a real between low and high.

*)
FUNCTION WORD_TO_RANGE : REAL
VAR_INPUT
	X : WORD;
	low : REAL;
	high : REAL;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[WORD_TO_RANGE := (high - low) * WORD_TO_REAL(X) * 0.00001525902189669640 + low;


(* revision history
hm	9. jan 2008	rev 1.0
	original version

hm	10. mar. 2009	rev 1.1
	improved code
*)
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
