<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CTRL_IN" Id="{3362e7f3-25eb-41b7-b268-399bbcf411be}" SpecialFunc="None">
    <Declaration><![CDATA[(*
version 1.0	2. jun 2008
programmer 	hugo
tested by		tobias


*)
FUNCTION CTRL_IN : REAL
VAR_INPUT
	SET_POINT, ACTUAL, NOISE : REAL;
END_VAR



]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* calculate the process error DIFF *)
CTRL_IN := DEAD_ZONE(SET_POINT - ACTUAL, NOISE);


(* revision history
hm 	2. jun. 2008 	rev 1.0
	original version

*)]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>