<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="R2_SET" Id="{5ac70d53-7b24-497e-9008-53e02cbe0dd5}" SpecialFunc="None">
    <Declaration><![CDATA[(*
version 1.1	10. mar. 2009
programmer 	hugo
tested by		tobias

R2_set sets a double precision real to a single real value.

*)
FUNCTION R2_SET : REAL2
VAR_INPUT
	X : REAL;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[R2_SET.RX := X;
R2_SET.R1 := 0.0;


(* revision history
hm	2. jun. 2008	rev 1.0
	original version

hm	10. mar. 2009	rev 1.1
	real constants updated to new systax using dot

*)]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
