<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_LIN" Id="{952a72b5-e8a1-4914-988b-b5c29b4c32cb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LIN : REAL
VAR_INPUT
	X : REAL;
	A : REAL;
	B : REAL;
END_VAR


(*
version 1.0	1 sep 2006
programmer 	hugo
tested by		tobias

this function calculates the linear equation f_lin = a*x + b

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_lin := A * X + B;

]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>