<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CABS" Id="{abbf67a0-050f-4d6f-8469-c70840bdd3ef}" SpecialFunc="None">
    <Declaration><![CDATA[(*
version 1.0	21 feb 2008
programmer 	hugo
tested by	oscat

this function the aboslute value of a complex number

*)
FUNCTION CABS : REAL
VAR_INPUT
	X : complex;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[CABS := HYPOT(x.re, x.im);


(* revision history
hm	21. feb 2008	rev 1.0
	original version

*)]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
