<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CSINH" Id="{feb11c35-86e0-450f-8ed6-06b459003954}" SpecialFunc="None">
    <Declaration><![CDATA[(*
version 1.0	21 feb 2008
programmer 	hugo
tested by	oscat

this function calculates the sinus function of a complex number

*)
FUNCTION CSINH : complex
VAR_INPUT
	X : complex;
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[CSINH.re := sinH(X.re) * COS(X.im);
CSINH.im := cosH(X.re) * SIN(X.im);


(* revision history
hm	21. feb 2008	rev 1.0
	original version

*)]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>